[package]
name = "lockfw"
version = "1.0.0"
edition = "2021"
resolver = "2"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
embedded-hal = "0.2.7"
lockbsp = { path = "../lockbsp" }
panic-halt = "0.2.0"
